---
permalink: /netlifyconfig.yml

---
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
media_library: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
